unique_name: Product Dimension
object_type: dimension
label: Product Dimension
description: "Product Line, Category, and Name"
type: standard

hierarchies:

  - unique_name: Product Dimension
    label: Product Hierarchy
    folder: Product Attributes

    levels:

      - unique_name: Product Line

      - unique_name: Product Category

        secondary_attributes:

          - unique_name: d_productsubcategoryId
            label: Product Subcategory ID
            description: ID of the product category
            dataset: dimproduct
            name_column: productsubcategorykey
            key_columns:
              - productsubcategorykey

      - unique_name: Product Key

        secondary_attributes:

          - unique_name: Product Name
            label: Product Name
            description: The Product Name
            folder: Product Attributes
            dataset: dimproduct
            name_column: englishproductname
            key_columns:
              - englishproductname
            sort_column: englishproductname

level_attributes:

  - unique_name: Product Category
    label: Product Category
    description: Product Sub Category
    dataset: dimproduct
    name_column: productsubcategoryname
    key_columns:
      - productline
      - productsubcategorykey

  - unique_name: Product Key
    label: Product Key
    description: Product Key
    is_unique_key: true
    dataset: dimproduct
    name_column: productkey
    key_columns:
      - productkey

  - unique_name: Product Line
    label: Product Line
    description: Product Line
    dataset: dimproduct
    name_column: productline
    key_columns:
      - productline
